import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Media - Centurion",
  description: "Generated by create next app",
};

// import { useTranslations } from "next-intl";
import MediaCard from "@/app/(marketing)/media/_components/media-card";
import MediaGallery from "@/app/(marketing)/media/_components/media-gallery";
import { bannerData } from "@/data/media";
import { Hero } from "@/components/hero";

export default function MediaPage() {
  // const t = useTranslations("HomePage");
  return (
    <>
      <Hero data={bannerData} />
      <MediaCard />
      <MediaGallery />
    </>
  );
}
