import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sustainability - Centuriation",
  description: "Generated by create next app",
};

import SustainabilityCommitment from "@/app/(marketing)/sustainability/_components/sustainability-commitment";
import CenturionWay from "@/app/(marketing)/sustainability/_components/centurion-way";
import OurCommitment from "@/app/(marketing)/sustainability/_components/our-commitment";
import { bannerData } from "@/data/sustainability";
import { Hero } from "@/components/hero";

export default function Sustainability() {
  return (
    <>
      <Hero data={bannerData} />
      <SustainabilityCommitment />
      <CenturionWay />
      <OurCommitment />
    </>
  );
}
