import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Media - Centuriation",
  description: "Generated by create next app",
};

// import { useTranslations } from "next-intl";
import MediaCard from "@/app/(root)/(routes)/media/_components/media-card";
import MediaGallery from "@/app/(root)/(routes)/media/_components/media-gallery";
import { Intro } from "./_components/intro";

export default function MediaPage() {
  // const t = useTranslations("HomePage");
  return (
    <>
      <Intro />
      <MediaCard />
      <MediaGallery />
    </>
  );
}
