import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy - Centurions",
  description: "Generated by create next app",
};

export default function PrivacyPolicyPage() {
  return (
    <section className="py-24 text-gray-800">
      <div className="container">
        <div className="w-full mx-auto px-4 sm:px-8 max-w-7xl">
          <div className="space-y-6">
            <div className="space-y-4">
              <h1 className="text-4xl sm:text-5xl font-semibold text-gray-900">
                Privacy Policy for Group Centurions
              </h1>
              <p className="text-gray-700 text-lg">
                At Group Centurions, accessible from groupcenturions.com, one of
                our main priorities is the privacy of our visitors. This Privacy
                Policy document contains types of information that is collected
                and recorded by Group Centurions and how we use it.
              </p>
              <p className="text-gray-700 text-lg">
                If you have additional questions or require more information
                about our Privacy Policy, do not hesitate to contact us.
              </p>
              <p className="text-gray-700 text-lg">
                This Privacy Policy applies only to our online activities and is
                valid for visitors to our website with regards to the
                information that they shared and/or collect in Group Centurions.
                This policy is not applicable to any information collected
                offline or via channels other than this website.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                Consent
              </h2>
              <p className="text-gray-700 text-lg">
                By using our website, you hereby consent to our Privacy Policy
                and agree to its terms.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                Information We Collect
              </h2>
              <p className="text-gray-700 text-lg">
                The personal information that you are asked to provide, and the
                reasons why you are asked to provide it, will be made clear to
                you at the point we ask you to provide your personal
                information.
              </p>
              <p className="text-gray-700 text-lg">
                If you contact us directly, we may receive additional
                information about you such as your name, email address, phone
                number, the contents of the message and/or attachments you may
                send us, and any other information you may choose to provide.
              </p>
              <p className="text-gray-700 text-lg">
                When you register for an Account, we may ask for your contact
                information, including items such as name, company name,
                address, email address, and telephone number.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                How We Use Your Information
              </h2>
              <dl className="space-y-4">
                <dt className="font-semibold text-lg">
                  We use the information we collect in various ways, including
                  to:
                </dt>
                <dd className="pl-6 text-gray-700 text-lg list-disc">
                  <ul className="space-y-2">
                    <li>Provide, operate, and maintain our website</li>
                    <li>Improve, personalize, and expand our website</li>
                    <li>Understand and analyze how you use our website</li>
                    <li>
                      Develop new products, services, features, and
                      functionality
                    </li>
                    <li>
                      Communicate with you, either directly or through one of
                      our partners, including for customer service, to provide
                      you with updates and other information relating to the
                      website, and for marketing and promotional purposes
                    </li>
                    <li>Send you emails</li>
                    <li>Find and prevent fraud</li>
                  </ul>
                </dd>
              </dl>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                Log Files
              </h2>
              <p className="text-gray-700 text-lg">
                Group Centurions follows a standard procedure of using log
                files. These files log visitors when they visit websites. All
                hosting companies do this and a part of hosting services&apost;
                analytics. The information collected by log files include
                internet protocol (IP) addresses, browser type, Internet Service
                Provider (ISP), date and time stamp, referring/exit pages, and
                possibly the number of clicks. These are not linked to any
                information that is personally identifiable. The purpose of the
                information is for analyzing trends, administering the site,
                tracking users&apost; movement on the website, and gathering
                demographic information.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                Cookies and Web Beacons
              </h2>
              <p className="text-gray-700 text-lg">
                Like any other website, Group Centurions uses
                &apost;cookies&apost;. These cookies are used to store
                information including visitors&apost; preferences, and the pages
                on the website that the visitor accessed or visited. The
                information is used to optimize the users&apost; experience by
                customizing our web page content based on visitors&apost;
                browser type and/or other information.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                Advertising Partners Privacy Policies
              </h2>
              <p className="text-gray-700 text-lg">
                You may consult this list to find the Privacy Policy for each of
                the advertising partners of Group Centurions.
              </p>
              <p className="text-gray-700 text-lg">
                Third-party ad servers or ad networks uses technologies like
                cookies, JavaScript, or Web Beacons that are used in their
                respective advertisements and links that appear on Group
                Centurions, which are sent directly to users&apost; browser.
                They automatically receive your IP address when this occurs.
                These technologies are used to measure the effectiveness of
                their advertising campaigns and/or to personalize the
                advertising content that you see on websites that you visit.
              </p>
              <p className="text-gray-700 text-lg">
                Note that Group Centurions has no access to or control over
                these cookies that are used by third-party advertisers.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                Third Party Privacy Policies
              </h2>
              <p className="text-gray-700 text-lg">
                Group Centurions&apost;s Privacy Policy does not apply to other
                advertisers or websites. Thus, we are advising you to consult
                the respective Privacy Policies of these third-party ad servers
                for more detailed information. It may include their practices
                and instructions about how to opt-out of certain options.
              </p>
              <p className="text-gray-700 text-lg">
                You can choose to disable cookies through your individual
                browser options. To know more detailed information about cookie
                management with specific web browsers, it can be found at the
                browsers&apost; respective websites.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                CCPA Privacy Rights (Do Not Sell My Personal Information)
              </h2>
              <p className="text-gray-700 text-lg">
                Under the CCPA, among other rights, California consumers have
                the right to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 text-lg space-y-2">
                <li>
                  Request that a business that collects a consumer&apost;s
                  personal data disclose the categories and specific pieces of
                  personal data that a business has collected about consumers.
                </li>
                <li>
                  Request that a business delete any personal data about the
                  consumer that a business has collected.
                </li>
                <li>
                  Request that a business that sells a consumer&apost;s personal
                  data, not sell the consumer&apost;s personal data.
                </li>
              </ul>
              <p className="text-gray-700 text-lg">
                If you make a request, we have one month to respond to you. If
                you would like to exercise any of these rights, please contact
                us.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                GDPR Data Protection Rights
              </h2>
              <p className="text-gray-700 text-lg">
                We would like to make sure you are fully aware of all of your
                data protection rights. Every user is entitled to the following:
              </p>
              <ul className="list-disc pl-6 text-gray-700 text-lg space-y-2">
                <li>
                  The right to access &ndash; You have the right to request
                  copies of your personal data. We may charge you a small fee
                  for this service.
                </li>
                <li>
                  The right to rectification &ndash; You have the right to
                  request that we correct any information you believe is
                  inaccurate. You also have the right to request that we
                  complete the information you believe is incomplete.
                </li>
                <li>
                  The right to erasure &ndash; You have the right to request
                  that we erase your personal data, under certain conditions.
                </li>
                <li>
                  The right to restrict processing &ndash; You have the right to
                  request that we restrict the processing of your personal data,
                  under certain conditions.
                </li>
                <li>
                  The right to object to processing &ndash; You have the right
                  to object to our processing of your personal data, under
                  certain conditions.
                </li>
                <li>
                  The right to data portability &ndash; You have the right to
                  request that we transfer the data that we have collected to
                  another organization, or directly to you, under certain
                  conditions.
                </li>
              </ul>
              <p className="text-gray-700 text-lg">
                If you make a request, we have one month to respond to you. If
                you would like to exercise any of these rights, please contact
                us.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl sm:text-4xl font-semibold text-gray-900">
                Children&apost;s Information
              </h2>
              <p className="text-gray-700 text-lg">
                Another part of our priority is adding protection for children
                while using the internet. We encourage parents and guardians to
                observe, participate in, and/or monitor and guide their online
                activity.
              </p>
              <p className="text-gray-700 text-lg">
                Group Centurions does not knowingly collect any Personal
                Identifiable Information from children under the age of 13. If
                you think that your child provided this kind of information on
                our website, we strongly encourage you to contact us immediately
                and we will do our best efforts to promptly remove such
                information from our records.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
