import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sustainability - Centuriation",
  description: "Generated by create next app",
};

import Wrapper from "@/components/layout/wrapper";
import Image from "next/image";
import SustainabilityCommitment from "@/components/sustainability/sustainability-commitment";
import CenturionWay from "@/components/sustainability/centurion-way";
import OurCommitment from "@/components/sustainability/our-commitment";
import BannerAnimation from "@/components/shared/banner-animation";

export default function Sustainability() {
  return (
    <>
      <div className="h-screen relative w-full flex items-center">
        <div className="absolute w-full h-full">
          <Image
            width={2000}
            height={2000}
            src="/assets/images/sustainability/sustainability-hero-img-img.webp"
            className="w-full h-full object-cover"
            alt="Sustainability Image"
          ></Image>
        </div>
        <div className="absolute inset-0 w-full h-full bg-black/60"></div>

        <Wrapper className="relative text-white font-semibold">
          <div className="max-w-[65ch] rounded bg-transparent backdrop-blur-sm">
            <h1 className="">Sustainability</h1>
            <h2 className="text-4.5xl mt-2 leading-none">
              Nurturing a Sustainable Future
            </h2>
            <p className="mt-4 text-md leading-tight">
              At Centurion, we believe that small actions lead to big changes.
              Just like nurturing a seed, we are committed to growing
              sustainable solutions that will benefit our planet for generations
              to come.
            </p>
          </div>
        </Wrapper>
        <BannerAnimation />
      </div>

      <SustainabilityCommitment />
      <CenturionWay />
      <OurCommitment />
    </>
  );
}
