import type { Metadata } from "next";
import Form from "@/app/(marketing)/contact/_components/form";
import GeneralInquiries from "@/app/(marketing)/contact/_components/general-inquiries";
import HeadOffice from "@/app/(marketing)/contact/_components/head-office";
import Map from "@/app/(marketing)/contact/_components/map";
import { useTranslations } from "next-intl";
import { Heading } from "@/components/heading";

export const metadata: Metadata = {
  title: "Contact - Centurions",
  description: "Generated by create next app",
};

export default function Contact() {
  const t = useTranslations("contact_us");
  return (
    <>
      <section className="section" data-padding="md">
        <div className="pt-14 md:pt-10">
          <div className="container">
            <div className="space-y-4">
              <div className="space-y-4">
                <Heading
                  as="h1"
                  size="4xl"
                  className="text-center text-2xl md:text-5xl font-medium font-title"
                >
                  {t("title")}
                </Heading>
                <p className="text-center max-w-2xl mx-auto">{t("content")}</p>
              </div>

              <div className="md:flex gap-10">
                <Form />
                <div className="flex-1">
                  <GeneralInquiries />
                  <HeadOffice />
                  <Map />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
