import type { Metadata } from "next";
import "@/styles/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Poppins } from "next/font/google";
import { Header } from "@/components/header";
import Footer from "@/components/footer";
import Lenis from "@/components/lenis";
import { Integration } from "@/components/intregation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Centurions",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <link rel="icon" href="/favicon.webp" />
      <body
        className={`${poppins.className} ${poppins.variable} font-body antialiased overflow-x-hidden`}
      >
        <Lenis>
          <NextIntlClientProvider messages={messages}>
            <Header />
            <main>{children}</main>
            <Footer />
            <Integration />
          </NextIntlClientProvider>
        </Lenis>
      </body>
    </html>
  );
}
