import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Career - Centuriation",
  description: "Generated by create next app",
};

// import { useTranslations } from "next-intl";
import CareerWork from "@/app/(marketing)/career/_components/career-work";
import JustCareer from "./_components/just-career";
import Accordion from "./_components/accordion";
import { bannerData } from "@/data/career";
import { Hero } from "@/components/hero";

export default function businesses() {
  // const t = useTranslations("HomePage");

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "We win and lose as teams?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "We are the market leader with a reputation for quality equipment supported by excellent service. All our employees are crucial to the success of the company.",
        },
      },
      {
        "@type": "Question",
        name: "We are proud to sign our names on our products?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "If you have questions about the application or suggestions for If you have questions about the application or suggestions forIf you have questions about the application or suggestions for If you have questions about the application or suggestions for.",
        },
      },
      {
        "@type": "Question",
        name: "We seek feedback early and often?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "If you have questions about the application or suggestions for If you have questions about the application or suggestions forIf you have questions about the application or suggestions for If you have questions about the application or suggestions for.",
        },
      },
    ],
  };

  return (
    <>
      <Hero data={bannerData} />

      <CareerWork />
      <JustCareer />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Accordion />
    </>
  );
}
