import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Business - Centurion",
  description: "Generated by create next app",
};

export default function BusinessLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="bg-gray-100">{children}</div>;
}
