import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sustainability - Centuriation",
  description: "Generated by create next app",
};

import Wrapper from "@/components/layout/wrapper";
import Image from "next/image";
import SustainabilityCommitment from "@/components/sustainability/sustainability-commitment";
import CenturionWay from "@/components/sustainability/centurion-way";
import OurCommitment from "@/components/sustainability/our-commitment";
import BannerAnimation from "@/components/shared/banner-animation";
import { Heading } from "@/components/heading";

export default function Sustainability() {
  return (
    <>
      <div className="h-screen relative w-full flex items-center">
        <div className="absolute w-full h-full">
          <Image
            width={2000}
            height={2000}
            src="/assets/images/sustainability/sustainability-hero-img-img.webp"
            className="w-full h-full object-cover"
            alt="Sustainability Image"
          ></Image>
        </div>
        <div className="absolute inset-0 w-full h-full bg-black/70"></div>

        <div className="container relative text-white">
          <div className="max-w-[60ch]">
            <Heading as="h1" size="base">
              Sustainability
            </Heading>
            <Heading as="h2" size="4.5xl">
              Nurturing a Sustainable Future
            </Heading>
            <p className="mt-4">
              At Centurion, we believe that small actions lead to big changes.
              Just like nurturing a seed, we are committed to growing
              sustainable solutions that will benefit our planet for generations
              to come.
            </p>
          </div>
        </div>
        <BannerAnimation />
      </div>

      <SustainabilityCommitment />
      <CenturionWay />
      <OurCommitment />
    </>
  );
}
